"""Canary tokens: believable FAKE secrets. Using them anywhere is a
high-fidelity, near-zero-false-positive intrusion signal."""

import os


class CanaryManager:
    def __init__(self, config):
        cfg = config.get("canary_tokens", {})
        self.usernames = cfg.get("usernames", ["svc_backup", "db_admin", "keypack"])
        self.passwords = cfg.get("passwords",
                                 ["B4ckup#2023!x", "Pr0dSQL!key77", "keypack-9f2c-44de"])
        self.deploy_dir = cfg.get("deploy_dir", "deployed_tokens")
        self.pairs = list(zip(self.usernames, self.passwords))
        self._pair_set = set(self.pairs)

    def is_canary_credential(self, username, password):
        return (username, password) in self._pair_set

    def is_canary_username(self, username):
        return username in set(self.usernames)

    def env_file_content(self):
        u, p = self.pairs[1] if len(self.pairs) > 1 else ("db_admin", "changeme")
        return (
            "# Production environment configuration - INTERNAL ONLY\n"
            "FLASK_ENV=production\n"
            "DATABASE_URL=mysql://app_user:AppUser2023@10.20.30.40:3306/corp_db\n"
            f"DB_ADMIN_USER={u}\n"
            f"DB_ADMIN_PASSWORD={p}\n"
            "SECRET_KEY=9f86d081884c7d659a2feaa0c55ad015\n"
            "AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE\n"
            "AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY\n"
        )

    def password_file_content(self):
        lines = ["# Legacy service accounts (keep private!)", ""]
        for u, p in self.pairs:
            lines.append(f"{u}:{p}")
        lines += ["", "# NOTE: usage of any account above is monitored."]
        return "\n".join(lines) + "\n"

    def deploy(self):
        os.makedirs(self.deploy_dir, exist_ok=True)
        with open(os.path.join(self.deploy_dir, ".env"), "w") as fh:
            fh.write(self.env_file_content())
        with open(os.path.join(self.deploy_dir, "backup_passwords.txt"), "w") as fh:
            fh.write(self.password_file_content())
        with open(os.path.join(self.deploy_dir, "README_FIRST.txt"), "w") as fh:
            fh.write(
                "These files are CANARY TOKENS generated by the AI Cyber Deception "
                "Engine.\nThey contain deliberately fake secrets. If anyone reads "
                "these files and\nthen tries the credentials, the engine raises a "
                "CRITICAL alert instantly.\n")
